<?php

/**
 * @file
 * Custom module which handles business logic for project entities.
 */

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\projects\Entity\Project;
use Drupal\projects\Access\ProjectFieldAccess;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\projects\Plugin\Field\ComputedProjectReferenceFieldItemList;

/**
 * Implements hook_entity_field_access().
 */
function projects_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  $entity = $items?->getEntity();
  if ($entity instanceof Project) {
    return ProjectFieldAccess::checkFieldAccess($entity, $operation, $field_definition, $account);
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_entity_base_field_info().
 */
function projects_entity_base_field_info(EntityTypeInterface $entity_type) {

  $fields = [];

  // Add projects base field to entity User.
  if ($entity_type->id() == 'user') {
    $fields['projects'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Computed Projects'))
      ->setSetting('target_type', 'project')
      ->setDescription(t('Computes the projects referencing this user.'))
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setComputed(TRUE)
      ->setClass(ComputedProjectReferenceFieldItemList::class);
  }

  return $fields;
}

/**
 * Implements hook_tokens().
 */
function projects_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {

  if ($type == 'project' && !empty($data['project'])) {
    /** @var \Drupal\projects\ProjectInterface $project */
    $project = $data['project'];

    foreach ($tokens as $name => $original) {
      $replacements[$original] = match ($name) {
        'project_id' => $project->id(),
        default => $name,
      };
    }
  }

  if ($type == 'project_result' && !empty($data['project_result'])) {
    /** @var \Drupal\child_entities\ChildEntityInterface $project_result */
    $project_result = $data['project_result'];
    $project = $project_result->getParentEntity();

    foreach ($tokens as $name => $original) {
      $replacements[$original] = match ($name) {
        'project_id' => $project->id(),
        default => $name,
      };
    }
  }

  return $replacements ?? [];
}

/**
 * Implements hook_jsonapi_ENTITY_TYPE_filter_access().
 */
function projects_jsonapi_project_filter_access(EntityTypeInterface $entity_type, AccountInterface $account) {
  return ([
    JSONAPI_FILTER_AMONG_ALL => AccessResult::allowed(),
    JSONAPI_FILTER_AMONG_PUBLISHED => AccessResult::allowed(),
    JSONAPI_FILTER_AMONG_OWN => AccessResult::allowed(),
  ]);
}
