<?php

/**
 * @file
 * Custom module which handles business logic for creative entities.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\creatives\CreativeFieldAccess;
use Drupal\creatives\Entity\Creative;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function creatives_entity_bundle_info_alter(&$bundles) {
  if (isset($bundles['user']['user'])) {
    $bundles['user']['user']['class'] = Creative::class;
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function creatives_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  $entity = $items?->getEntity();
  if ($entity instanceof Creative) {
    return CreativeFieldAccess::checkFieldAccess($entity, $operation, $field_definition, $account);
  }
  return AccessResult::neutral();
}
