<?php

/**
 * @file
 */

use Drupal\views\ViewExecutable;

/**
 *
 */
function manager_preprocess_views_view_table(&$variables) {
  foreach ($variables['rows'] as &$row) {
    $entity = $row['#row']->_entity ?? NULL;
    if ($entity && $entity->bundle() === 'project') {
      $row['#attributes']['class'][] = 'js-project-row';
      $row['#attributes']['data-id'] = $entity->id();
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function manager_views_pre_render(ViewExecutable $view): void {
  if ($view->id() === 'project_manager') {
    $view->element['#attached']['library'][] = 'manager/core';
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function manager_theme_suggestions_context_pane_alter(&$suggestions, $variables): void {
  if (!empty($variables['elements']['#type'])) {
    $suggestions[] = 'context_pane__' . $variables['elements']['#type'];
  }
}
