<?php

/**
 * @file
 */

use Drupal\views\Plugin\views\cache\CachePluginBase;
use Drupal\views\ViewExecutable;

/**
 *
 */
function manager_preprocess_views_view_table(&$variables) {
  foreach ($variables['rows'] as &$row) {
    $entity = $row['#row']->_entity ?? NULL;
    if ($entity && $entity->bundle() === 'project') {
      $row['#attributes']['class'][] = 'js-project-row';
      $row['#attributes']['data-id'] = $entity->id();
    }
  }
}

/**
 * Implements hook_theme().
 */
function manager_theme(array $existing, $type, $theme, $path): array {
  return [
    'context_pane' => [
      'render element' => 'elements',
      'template' => 'context-pane',
      'path' => "$path/templates",
    ],
  ];
}

/**
 * Implements hook_views_pre_render().
 */
function manager_views_pre_render(ViewExecutable $view): void {
  if ($view->id() === 'project_manager') {
    $view->element['#attached']['library'][] = 'manager/core';
  }
}
