packages:
    asm89/stack-cors: v2.2.0
    behat/mink: v1.12.0
    behat/mink-browserkit-driver: v2.2.0
    brick/math: 0.12.1
    chi-teck/drupal-code-generator: 3.6.1
    colinodell/psr-testlogger: v1.3.0
    composer/ca-bundle: 1.5.4
    composer/class-map-generator: 1.5.0
    composer/composer: 2.8.4
    composer/installers: v1.12.0
    composer/metadata-minifier: 1.0.0
    composer/pcre: 3.3.2
    composer/semver: 3.4.3
    composer/spdx-licenses: 1.5.8
    composer/xdebug-handler: 3.0.5
    consolidation/annotated-command: 4.10.1
    consolidation/config: 2.1.2
    consolidation/filter-via-dot-access-data: 2.0.2
    consolidation/log: 3.1.0
    consolidation/output-formatters: 4.6.0
    consolidation/robo: 4.0.6
    consolidation/self-update: 2.2.0
    consolidation/site-alias: 4.1.1
    consolidation/site-process: 5.4.2
    cweagans/composer-patches: 1.7.3
    dealerdirect/phpcodesniffer-composer-installer: v0.7.2
    defuse/php-encryption: v2.4.0
    dekor/php-array-table: '2.0'
    dflydev/dot-access-data: v3.0.3
    doctrine/annotations: 1.14.4
    doctrine/common: 3.4.5
    doctrine/deprecations: 1.1.4
    doctrine/event-manager: 2.0.1
    doctrine/instantiator: 2.0.0
    doctrine/lexer: 2.1.1
    doctrine/persistence: 3.4.0
    dompdf/php-font-lib: 1.0.1
    drupal/admin_toolbar: 3.5.1
    drupal/coder: 8.3.26
    drupal/config_ignore: 3.3.0
    drupal/consumer_image_styles: 4.0.10
    drupal/consumers: 1.19.0
    drupal/core: 10.3.10
    drupal/core-composer-scaffold: 10.3.10
    drupal/core-dev: 10.3.10
    drupal/core-project-message: 10.3.10
    drupal/core-recommended: 10.3.10
    drupal/core-vendor-hardening: 10.3.10
    drupal/devel: 5.3.1
    drupal/devel_mail_logger: 2.0.0
    drupal/entity: 1.5.0
    drupal/file_mdm: 3.1.0
    drupal/filefield_paths: 1.0.0-beta8
    drupal/gin: 3.0.0-rc15
    drupal/gin_toolbar: 1.0.0-rc7
    drupal/image_style_warmer: 1.3.0-rc1
    drupal/imagemagick: 4.0.2
    drupal/jsonapi_boost: 2.0.4
    drupal/jsonapi_cross_bundles: 1.1.0
    drupal/jsonapi_extras: 3.26.0
    drupal/jsonapi_include: 1.8.0
    drupal/mail_login: 4.0.3
    drupal/mailsystem: 4.5.0
    drupal/multivalue_form_element: 1.0.0-beta6
    drupal/openapi: 2.2.0
    drupal/openapi_jsonapi: 3.0.5
    drupal/openapi_ui: 1.0.0-rc5
    drupal/openapi_ui_redoc: 1.0.0-rc5
    drupal/restui: 1.22.0
    drupal/schemata: 1.0.0
    drupal/schemata_json_schema: 1.0.0
    drupal/simple_oauth: 5.2.5
    drupal/sophron: 2.1.0
    drupal/subrequests: 3.0.12
    drupal/upgrade_status: 4.3.6
    drupal/user_bundle: 1.2.0
    drupal/warmer: 2.0.14
    drush/drush: 12.5.3
    e0ipso/shaper: 1.2.5
    egulias/email-validator: 4.0.2
    fakerphp/faker: v1.24.1
    fileeye/mimemap: 2.2.0
    fileeye/pel: 0.10.0
    galbar/jsonpath: 1.3.1
    google/protobuf: v4.29.1
    grasmash/expander: 3.0.1
    grasmash/yaml-cli: 3.2.1
    guzzlehttp/guzzle: 7.8.2
    guzzlehttp/promises: 2.0.4
    guzzlehttp/psr7: 2.6.3
    joachim-n/composer-manifest: 1.1.6
    justinrainbow/json-schema: 5.3.0
    lcobucci/clock: 3.0.0
    lcobucci/jwt: 4.3.0
    league/container: 4.2.4
    league/event: 2.2.0
    league/oauth2-server: 8.5.4
    league/uri: 7.5.1
    league/uri-interfaces: 7.5.0
    lullabot/mink-selenium2-driver: v1.7.4
    lullabot/php-webdriver: v2.0.6
    masterminds/html5: 2.9.0
    mck89/peast: v1.16.3
    mglaman/phpstan-drupal: 1.3.2
    micheh/phpcs-gitlab: 1.1.0
    mikey179/vfsstream: v1.6.12
    myclabs/deep-copy: 1.12.1
    nikic/php-parser: v5.3.1
    nyholm/psr7-server: 1.1.0
    open-telemetry/api: 1.1.2
    open-telemetry/context: 1.1.0
    open-telemetry/exporter-otlp: 1.1.0
    open-telemetry/gen-otlp-protobuf: 1.2.1
    open-telemetry/sdk: 1.1.2
    open-telemetry/sem-conv: 1.27.1
    paragonie/random_compat: v9.99.100
    pear/archive_tar: 1.5.0
    pear/console_getopt: v1.4.3
    pear/pear-core-minimal: v1.10.16
    pear/pear_exception: v1.0.2
    phar-io/manifest: 2.0.4
    phar-io/version: 3.2.1
    phootwork/collection: v3.2.3
    phootwork/lang: v3.2.3
    php-http/discovery: 1.20.0
    php-http/guzzle7-adapter: 1.1.0
    php-http/httplug: 2.4.1
    php-http/promise: 1.3.1
    phpcompatibility/php-compatibility: 9.3.5
    phpdocumentor/reflection-common: 2.2.0
    phpdocumentor/reflection-docblock: 5.6.1
    phpdocumentor/type-resolver: 1.10.0
    phpowermove/docblock: v4.0
    phpspec/prophecy: v1.20.0
    phpspec/prophecy-phpunit: v2.3.0
    phpstan/extension-installer: 1.4.3
    phpstan/phpdoc-parser: 1.33.0
    phpstan/phpstan: 1.12.12
    phpstan/phpstan-deprecation-rules: 1.2.1
    phpstan/phpstan-phpunit: 1.4.1
    phpunit/php-code-coverage: 9.2.32
    phpunit/php-file-iterator: 3.0.6
    phpunit/php-invoker: 3.1.1
    phpunit/php-text-template: 2.0.4
    phpunit/php-timer: 5.0.3
    phpunit/phpunit: 9.6.22
    psr/cache: 3.0.0
    psr/clock: 1.0.0
    psr/container: 2.0.2
    psr/event-dispatcher: 1.0.0
    psr/http-client: 1.0.3
    psr/http-factory: 1.1.0
    psr/http-message: '2.0'
    psr/log: 3.0.2
    psy/psysh: v0.12.7
    ralouphie/getallheaders: 3.0.3
    ramsey/collection: 2.0.0
    ramsey/uuid: 4.7.6
    react/promise: v3.2.0
    sebastian/cli-parser: 1.0.2
    sebastian/code-unit: 1.0.8
    sebastian/code-unit-reverse-lookup: 2.0.3
    sebastian/comparator: 4.0.8
    sebastian/complexity: 2.0.3
    sebastian/diff: 4.0.6
    sebastian/environment: 5.1.5
    sebastian/exporter: 4.0.6
    sebastian/global-state: 5.0.7
    sebastian/lines-of-code: 1.0.4
    sebastian/object-enumerator: 4.0.4
    sebastian/object-reflector: 2.0.4
    sebastian/recursion-context: 4.0.5
    sebastian/resource-operations: 3.0.4
    sebastian/type: 3.2.1
    sebastian/version: 3.0.2
    seld/jsonlint: 1.11.0
    seld/phar-utils: 1.2.1
    seld/signal-handler: 2.0.2
    sirbrillig/phpcs-variable-analysis: v2.11.21
    slevomat/coding-standard: 8.15.0
    squizlabs/php_codesniffer: 3.11.2
    steverhoades/oauth2-openid-connect-server: v2.6.1
    symfony/browser-kit: v6.4.13
    symfony/console: v6.4.15
    symfony/css-selector: v6.4.13
    symfony/dependency-injection: v6.4.16
    symfony/deprecation-contracts: v3.5.1
    symfony/dom-crawler: v6.4.16
    symfony/error-handler: v6.4.14
    symfony/event-dispatcher: v6.4.13
    symfony/event-dispatcher-contracts: v3.5.1
    symfony/filesystem: v6.4.13
    symfony/finder: v6.4.13
    symfony/http-foundation: v6.4.16
    symfony/http-kernel: v6.4.16
    symfony/lock: v6.4.13
    symfony/mailer: v6.4.13
    symfony/mime: v6.4.13
    symfony/phpunit-bridge: v6.4.16
    symfony/polyfill-ctype: v1.29.0
    symfony/polyfill-iconv: v1.29.0
    symfony/polyfill-intl-grapheme: v1.29.0
    symfony/polyfill-intl-idn: v1.29.0
    symfony/polyfill-intl-normalizer: v1.29.0
    symfony/polyfill-mbstring: v1.29.0
    symfony/polyfill-php72: v1.31.0
    symfony/polyfill-php73: v1.31.0
    symfony/polyfill-php80: v1.31.0
    symfony/polyfill-php81: v1.31.0
    symfony/polyfill-php82: v1.31.0
    symfony/polyfill-php83: v1.29.0
    symfony/process: v6.4.15
    symfony/psr-http-message-bridge: v6.4.13
    symfony/routing: v6.4.16
    symfony/serializer: v6.4.15
    symfony/service-contracts: v3.5.1
    symfony/string: v6.4.15
    symfony/translation-contracts: v3.5.1
    symfony/validator: v6.4.16
    symfony/var-dumper: v6.4.15
    symfony/var-exporter: v6.4.13
    symfony/yaml: v6.4.13
    tbachert/spi: v1.0.2
    theseer/tokenizer: 1.2.3
    twig/twig: v3.14.2
    vipnytt/sitemapparser: v1.3.0
    webflo/drupal-finder: 1.3.1
    webmozart/assert: 1.11.0
