packages:
    asm89/stack-cors: v2.4.0
    behat/mink: v1.13.0
    behat/mink-browserkit-driver: v2.3.0
    brick/math: 1.0.0
    chi-teck/drupal-code-generator: 4.2.0
    colinodell/psr-testlogger: v1.3.1
    composer/ca-bundle: 1.5.14
    composer/class-map-generator: 1.8.0
    composer/composer: 2.10.3
    composer/installers: v1.12.0
    composer/metadata-minifier: 1.0.1
    composer/pcre: 3.4.0
    composer/semver: 3.4.4
    composer/spdx-licenses: 1.6.0
    composer/xdebug-handler: 3.0.5
    consolidation/annotated-command: 4.10.5
    consolidation/config: 3.2.1
    consolidation/filter-via-dot-access-data: 2.0.3
    consolidation/log: 3.1.2
    consolidation/output-formatters: 4.7.1
    consolidation/robo: 5.1.1
    consolidation/site-alias: 4.1.3
    consolidation/site-process: 6.1.0
    cweagans/composer-patches: 1.7.3
    dealerdirect/phpcodesniffer-composer-installer: v0.7.2
    defuse/php-encryption: v2.4.0
    dflydev/dot-access-data: v3.0.3
    doctrine/deprecations: 1.1.6
    doctrine/instantiator: 2.0.0
    doctrine/lexer: 3.0.3
    dompdf/php-font-lib: 1.0.2
    drupal/admin_toolbar: 3.6.3
    drupal/coder: 8.3.31
    drupal/config_ignore: 3.4.0
    drupal/consumer_image_styles: 4.0.10
    drupal/consumers: 1.24.0
    drupal/core: 11.4.9
    drupal/core-composer-scaffold: 11.4.9
    drupal/core-dev: 11.4.9
    drupal/core-project-message: 11.4.9
    drupal/core-recommended: 11.4.9
    drupal/core-vendor-hardening: 11.4.9
    drupal/entity: 1.8.0
    drupal/file_mdm: 3.2.0
    drupal/filefield_paths: 1.0.0
    drupal/gin: 5.0.15
    drupal/gin_toolbar: 3.0.3
    drupal/image_style_warmer: 1.3.0
    drupal/imagemagick: 5.0.1
    drupal/jsonapi_boost: 2.0.4
    drupal/jsonapi_cross_bundles: 1.2.0
    drupal/jsonapi_extras: 3.28.0
    drupal/jsonapi_include: 2.0.0
    drupal/mail_login: 4.2.2
    drupal/mailsystem: 4.5.0
    drupal/multivalue_form_element: 1.0.0-beta8
    drupal/nomarkup: 1.0.6
    drupal/openapi: 2.3.0
    drupal/openapi_jsonapi: 3.0.6
    drupal/openapi_ui: 1.0.0-rc5
    drupal/openapi_ui_redoc: 1.0.0-rc5
    drupal/responsive_favicons: 4.0.0
    drupal/restui: 1.22.0
    drupal/schemata: 1.1.0
    drupal/schemata_json_schema: 1.1.0
    drupal/simple_oauth: 6.1.1
    drupal/sophron: 3.1.1
    drupal/subrequests: 3.0.12
    drupal/twig_field_value: 2.0.5
    drupal/twig_tweak: 3.4.2
    drupal/user_bundle: 1.5.0
    drupal/warmer: 2.0.14
    drush/drush: 13.8.0
    e0ipso/shaper: 1.2.7
    egulias/email-validator: 4.0.4
    fakerphp/faker: v1.24.1
    fileeye/mimemap: 2.2.6
    fileeye/pel: 0.12.1
    galbar/jsonpath: 1.3.1
    google/protobuf: v5.36.2
    grasmash/expander: 3.0.1
    grasmash/yaml-cli: 3.2.1
    guzzlehttp/guzzle: 7.15.5
    guzzlehttp/promises: 2.5.3
    guzzlehttp/psr7: 2.13.1
    jangregor/phpstan-prophecy: 2.3.0
    joachim-n/composer-manifest: 1.1.7
    justinrainbow/json-schema: 6.8.2
    laravel/prompts: v0.3.25
    lcobucci/clock: 3.5.0
    lcobucci/jwt: 5.6.0
    league/container: 4.2.5
    league/event: 3.0.3
    league/oauth2-server: 9.4.1
    league/uri: 7.8.1
    league/uri-interfaces: 7.8.1
    lullabot/mink-selenium2-driver: v1.7.4
    lullabot/php-webdriver: v2.0.7
    marc-mabe/php-enum: v4.7.2
    masterminds/html5: 2.10.1
    mck89/peast: v1.17.7
    mglaman/composer-drupal-lenient: 2.0.0
    mglaman/phpstan-drupal: 2.2.2
    micheh/phpcs-gitlab: 2.1.0
    mikey179/vfsstream: v1.6.12
    myclabs/deep-copy: 1.14.0
    nikic/php-parser: v5.9.0
    nyholm/psr7-server: 1.1.0
    open-telemetry/api: 1.10.0
    open-telemetry/context: 1.5.0
    open-telemetry/exporter-otlp: 1.4.0
    open-telemetry/gen-otlp-protobuf: 1.10.0
    open-telemetry/sdk: 1.15.0
    open-telemetry/sem-conv: 1.44.0
    paragonie/random_compat: v9.99.100
    pear/archive_tar: 1.6.1
    pear/console_getopt: v1.4.3
    pear/pear-core-minimal: v1.10.18
    pear/pear_exception: v1.0.2
    phar-io/manifest: 2.0.4
    phar-io/version: 3.2.1
    phootwork/collection: v3.2.3
    phootwork/lang: v3.2.3
    php-http/discovery: 1.20.0
    php-http/guzzle7-adapter: 1.1.0
    php-http/httplug: 2.4.1
    php-http/promise: 1.3.1
    php-parallel-lint/php-parallel-lint: v1.4.0
    php-tuf/composer-stager: v2.1.1
    phpcompatibility/php-compatibility: 9.3.5
    phpdocumentor/reflection-common: 2.2.1
    phpdocumentor/reflection-docblock: 6.0.3
    phpdocumentor/type-resolver: 2.1.0
    phpowermove/docblock: v4.0
    phpro/grumphp-shim: v2.25.0
    phpspec/prophecy: v1.26.1
    phpspec/prophecy-phpunit: v2.5.0
    phpstan/extension-installer: 1.4.3
    phpstan/phpdoc-parser: 2.3.6
    phpstan/phpstan: 2.3.1
    phpstan/phpstan-deprecation-rules: 2.0.5
    phpstan/phpstan-phpunit: 2.1.1
    phpunit/php-code-coverage: 11.0.12
    phpunit/php-file-iterator: 5.1.1
    phpunit/php-invoker: 5.0.1
    phpunit/php-text-template: 4.0.1
    phpunit/php-timer: 7.0.1
    phpunit/phpunit: 11.5.57
    psr/clock: 1.0.0
    psr/container: 2.0.2
    psr/event-dispatcher: 1.0.0
    psr/http-client: 1.0.3
    psr/http-factory: 1.1.0
    psr/http-message: '2.0'
    psr/http-server-handler: 1.0.2
    psr/http-server-middleware: 1.0.2
    psr/log: 3.0.2
    psy/psysh: v0.12.24
    ralouphie/getallheaders: 3.0.3
    ramsey/collection: 2.1.1
    ramsey/uuid: 4.9.4
    react/promise: v3.3.0
    revolt/event-loop: v1.0.9
    roave/security-advisories: 'dev-latest:96cf8b77ade13bb6638d1b26d48a72deec75b7d0'
    sebastian/cli-parser: 3.0.2
    sebastian/code-unit: 3.0.3
    sebastian/code-unit-reverse-lookup: 4.0.1
    sebastian/comparator: 6.3.3
    sebastian/complexity: 4.0.1
    sebastian/diff: 6.0.2
    sebastian/environment: 7.2.1
    sebastian/exporter: 6.3.2
    sebastian/global-state: 7.0.2
    sebastian/lines-of-code: 3.0.1
    sebastian/object-enumerator: 6.0.1
    sebastian/object-reflector: 4.0.1
    sebastian/recursion-context: 6.0.3
    sebastian/type: 5.1.3
    sebastian/version: 5.0.2
    seld/jsonlint: 1.12.1
    seld/phar-utils: 1.2.3
    seld/signal-handler: 2.0.2
    sirbrillig/phpcs-variable-analysis: v2.13.0
    slevomat/coding-standard: 8.22.1
    squizlabs/php_codesniffer: 3.13.6
    staabm/side-effects-detector: 1.0.5
    steverhoades/oauth2-openid-connect-server: v3.0.1
    symfony/browser-kit: v7.4.17
    symfony/console: v7.4.20
    symfony/css-selector: v7.4.18
    symfony/dependency-injection: v7.4.20
    symfony/deprecation-contracts: v3.7.1
    symfony/dom-crawler: v7.4.17
    symfony/error-handler: v7.4.20
    symfony/event-dispatcher: v7.4.17
    symfony/event-dispatcher-contracts: v3.7.1
    symfony/filesystem: v7.4.18
    symfony/finder: v7.4.20
    symfony/http-foundation: v7.4.20
    symfony/http-kernel: v7.4.20
    symfony/lock: v7.4.20
    symfony/mailer: v7.4.19
    symfony/mime: v7.4.19
    symfony/polyfill-ctype: v1.37.0
    symfony/polyfill-iconv: v1.43.0
    symfony/polyfill-intl-grapheme: v1.43.0
    symfony/polyfill-intl-idn: v1.43.0
    symfony/polyfill-intl-normalizer: v1.43.0
    symfony/polyfill-mbstring: v1.43.0
    symfony/polyfill-php73: v1.37.0
    symfony/polyfill-php80: v1.43.0
    symfony/polyfill-php81: v1.38.1
    symfony/polyfill-php82: v1.43.0
    symfony/polyfill-php83: v1.43.0
    symfony/polyfill-php84: v1.43.0
    symfony/polyfill-php85: v1.43.0
    symfony/polyfill-php86: v1.43.0
    symfony/process: v7.4.19
    symfony/psr-http-message-bridge: v7.4.8
    symfony/routing: v7.4.20
    symfony/runtime: v7.4.14
    symfony/serializer: v7.4.20
    symfony/service-contracts: v3.7.3
    symfony/string: v7.4.19
    symfony/translation-contracts: v3.7.1
    symfony/validator: v7.4.20
    symfony/var-dumper: v7.4.18
    symfony/var-exporter: v7.4.18
    symfony/yaml: v7.4.20
    tbachert/spi: v1.0.5
    theseer/tokenizer: 1.3.1
    twig/html-extra: v3.29.0
    twig/twig: v3.30.0
    vipnytt/sitemapparser: v1.3.2
    webflo/drupal-finder: 1.3.1
    webmozart/assert: 2.5.0
    weitzman/drupal-test-traits: 2.7.2
