<?php

/**
 * @file
 * Custom module which handles business logic for organization entities.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\organizations\Entity\Organization;
use Drupal\organizations\OrganizationFieldAccess;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function organizations_entity_bundle_info_alter(&$bundles) {
  if (isset($bundles['user']['organization'])) {
    $bundles['user']['organization']['class'] = Organization::class;
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function organizations_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  $entity = $items?->getEntity();
  if ($entity instanceof Organization) {
    return OrganizationFieldAccess::checkFieldAccess($entity, $operation, $field_definition, $account);
  }
  return AccessResult::neutral();
}
