mailer.transactional_email.*:
  type: config_entity
  label: Transactional Email
  mapping:
    uuid:
      type: string
    id:
      type: string
      label: Machine Name
    label:
      type: label
      label: Label
    subject:
      type: string
      label: Subject
      translatable: true
    body:
      type: string
      label: Body
      translatable: true
    tokens:
      type: sequence
      label: List of Tokens
      sequence:
        type: string
        label: Token

