<?php

/**
 * @file
 * Provides hooks to document progress in academy.
 */

use Drupal\Core\Entity\EntityStorageException;
use Drupal\Component\Plugin\Exception\PluginNotFoundException;
use Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Access\AccessResultInterface;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Session\AccountInterface;
use Drupal\courses\Entity\Course;
use Drupal\lectures\Entity\Lecture;
use Drupal\progress\Plugin\Field\CompletedFieldItemList;
use Drupal\progress\Plugin\Field\CurrentLectureFieldItemList;
use Drupal\progress\Plugin\Field\ProgressFieldItemList;
use Drupal\progress\Plugin\Field\UnlockedFieldItemList;
use Drupal\Core\Utility\Error;

/**
 * Implements hook_entity_base_field_info().
 */
function progress_entity_base_field_info(EntityTypeInterface $entity_type) {

  $fields = [];

  // Add paragraphs base field to entity Lecture and Course.
  if ($entity_type->id() == 'lecture' || $entity_type->id() == 'course') {
    $fields['completed'] = BaseFieldDefinition::create('cacheable_boolean')
      ->setLabel(t('Completed'))
      ->setDescription(t('Computes the completed status by user.'))
      ->setComputed(TRUE)
      ->setClass(CompletedFieldItemList::class);
    $fields['unlocked'] = BaseFieldDefinition::create('cacheable_boolean')
      ->setLabel(t('Unlocked'))
      ->setDescription(t('Computes the unlocked status by user.'))
      ->setComputed(TRUE)
      ->setClass(UnlockedFieldItemList::class);
  }

  // Add paragraphs base field to entity Course.
  if ($entity_type->id() == 'course') {
    $fields['progress'] = BaseFieldDefinition::create('cacheable_integer')
      ->setLabel(t('Progress'))
      ->setDescription(t('Computes the progress status by user.'))
      ->setComputed(TRUE)
      ->setClass(ProgressFieldItemList::class);
    $fields['current_lecture'] = BaseFieldDefinition::create('cacheable_string')
      ->setLabel(t('Current Lecture'))
      ->setDescription(t('Computes the last unlocked lecture by user.'))
      ->setComputed(TRUE)
      ->setClass(CurrentLectureFieldItemList::class);
  }

  return $fields;
}

/**
 * Implements hook_child_entities_check_access().
 *
 * @see \Drupal\child_entities\ChildEntityAccessControlHandler
 */
function progress_child_entities_check_access(AccessResultInterface &$access, ContentEntityInterface $origin, AccountInterface $account) {

  // Skip, if this is an editor.
  if ($account->hasPermission('manage courses')) {
    return;
  }

  // Check enrollment status. Therefore, from an access point of view, all
  // contents of the course are revealed once a user enrolls into a course.
  if ($access->isAllowed()) {
    $access = AccessResult::allowedIf(\Drupal::service('progress.manager')
      ->isUnlocked($origin, $account));
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * Delete all relevant progress entries when lecture is deleted.
 */
function progress_lecture_delete(EntityInterface $entity) {

  if ($entity instanceof Lecture) {
    try {
      $progresses = \Drupal::entityTypeManager()->getStorage('lecture_progress')
        ->loadByProperties(['lecture' => $entity->id()]);
      foreach ($progresses as $progress) {
        $progress->delete();
      }
    }
    catch (InvalidPluginDefinitionException | PluginNotFoundException | EntityStorageException $e) {
      $variables = Error::decodeException($e);
      $variables['%id'] = $entity->id();
      \Drupal::logger('academy')
        ->error('Unable to delete submissions for lecture with ID %id.', $variables);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * Delete all relevant progress entries when course is deleted.
 */
function progress_course_delete(EntityInterface $entity) {

  if ($entity instanceof Course) {
    try {
      $progresses = \Drupal::entityTypeManager()->getStorage('course_progress')
        ->loadByProperties(['course' => $entity->id()]);
      foreach ($progresses as $progress) {
        $progress->delete();
      }
    }
    catch (InvalidPluginDefinitionException | PluginNotFoundException | EntityStorageException $e) {
      $variables = Error::decodeException($e);
      $variables['%id'] = $entity->id();
      \Drupal::logger('academy')
        ->error('Unable to delete submissions for course with ID %id.', $variables);
    }
  }
}
