<?php

/**
 * @file
 * Provides hook implementations for the Youvo Lifecycle module.
 */

/**
 * Implements hook_field_widget_info_alter().
 */
function youvo_lifecycle_field_widget_info_alter(array &$info) {
  $info['options_select']['field_types'][] = 'youvo_lifecycle_item';
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function youvo_lifecycle_field_formatter_info_alter(array &$info) {
  $info['list_default']['field_types'][] = 'youvo_lifecycle_item';
}
