<?php

/**
 * @file
 * Provides a logbook.
 */

/**
 * Implements hook_theme().
 */
function logbook_theme() {
  return [
    'log' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for log templates.
 */
function template_preprocess_log(array &$variables) {
  /** @var \Drupal\logbook\LogInterface $log */
  $log = $variables['elements']['#log'];
  $variables['log'] = $log;
  $variables['author'] = $log->getOwner();
  $variables['manager'] = $log->getManager();
  $variables['creatives'] = $log->getCreatives();
  $variables['project'] = $log->getProject();
  $variables['message'] = $log->getMessage();
  $variables['text']['#markup'] = $log->getMarkup();
}
