<?php

/**
 * @file
 * Provides hooks for a lecture entity type.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\lectures\Entity\Lecture;

/**
 * Implements hook_entity_operation().
 */
function lectures_entity_operation(EntityInterface $entity) {
  $operations = [];
  if ($entity instanceof Lecture &&
    \Drupal::service('module_handler')->moduleExists('paragraphs')) {
    $operations['add_paragraphs'] = [
      'title' => t('Paragraphs'),
      'url' => Url::fromRoute('entity.paragraph.collection', ["lecture" => $entity->id()]),
      'weight' => 1,
    ];
  }
  return $operations;
}
