<?php

/**
 * @file
 * Provides hooks for a lecture entity type.
 */

use Drupal\child_entities\Plugin\Field\ComputedChildEntityReferenceFieldItemList;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\lectures\Entity\Lecture;

/**
 * Implements hook_entity_base_field_info().
 */
function lectures_entity_base_field_info(EntityTypeInterface $entity_type) {

  $fields = [];

  // Add lectures base field to entity Course.
  if ($entity_type->id() == 'course') {
    $fields['lectures'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Computed Children.'))
      ->setSetting('target_type', 'lecture')
      ->setDescription(t('Computes the lectures referencing this course.'))
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setComputed(TRUE)
      ->setClass(ComputedChildEntityReferenceFieldItemList::class);
  }

  return $fields;
}

/**
 * Implements hook_entity_operation_alter().
 */
function lectures_entity_operation_alter(array &$operations, EntityInterface $entity) {
  // Overwrite edit and delete to avoid destination.
  if ($entity instanceof Lecture) {
    $operations['edit']['url'] = Url::fromRoute('entity.lecture.edit_form', [
      'course' => $entity->getParentEntity()->id(),
      'lecture' => $entity->id(),
    ]);
    $operations['delete']['url'] = Url::fromRoute('entity.lecture.delete_form', [
      'course' => $entity->getParentEntity()->id(),
      'lecture' => $entity->id(),
    ]);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lectures_form_course_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add abort button.
  $url = Url::fromRoute('entity.lecture.collection');
  lectures_add_abort_button($form, $url);

  // Alter redirect.
  $form['actions']['submit']['#submit'][] = 'lectures_form_course_edit_form_redirect';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lectures_form_course_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Add abort button.
  /** @var \Drupal\Core\Entity\ContentEntityForm $form_object */
  $form_object = $form_state->getFormObject();
  $course = $form_object->getEntity();
  $url = Url::fromRoute('entity.lecture.collection', [], [
    'query' => ['cr' => $course->id()],
    'fragment' => 'edit-course-' . $course->id(),
  ]);
  lectures_add_abort_button($form, $url);

  // Alter redirect.
  $form['actions']['submit']['#submit'][] = 'lectures_form_course_edit_form_redirect';
}

/**
 * Set redirect for course form.
 */
function lectures_form_course_edit_form_redirect($form, FormStateInterface $form_state) {

  /** @var \Drupal\Core\Entity\ContentEntityForm $form_object */
  $form_object = $form_state->getFormObject();
  $course = $form_object->getEntity();
  $form_state->setRedirect('entity.lecture.collection', [], [
    'query' => ['cr' => $course->id()],
    'fragment' => 'edit-course-' . $course->id(),
  ]);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lectures_form_lecture_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $course = \Drupal::service('current_route_match')->getParameter('course');
  $url = Url::fromRoute('entity.lecture.collection', [], [
    'query' => ['cr' => $course->id()],
    'fragment' => 'edit-course-' . $course->id(),
  ]);
  lectures_add_abort_button($form, $url);

  // Alter redirect.
  $form['actions']['submit']['#submit'][] = 'lectures_form_lecture_edit_form_redirect';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lectures_form_lecture_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Add abort button.
  /** @var \Drupal\child_entities\ChildEntityInterface $lecture */
  $lecture = \Drupal::service('current_route_match')->getParameter('lecture');
  $url = Url::fromRoute('entity.paragraph.collection', [
    'course' => $lecture->getParentEntity()->id(),
    'lecture' => $lecture->id(),
  ]);
  lectures_add_abort_button($form, $url);

  // Alter redirect.
  $form['actions']['submit']['#submit'][] = 'lectures_form_lecture_edit_form_redirect';
}

/**
 * Set redirect for lecture form.
 */
function lectures_form_lecture_edit_form_redirect($form, FormStateInterface $form_state) {

  /** @var \Drupal\Core\Entity\ContentEntityForm $form_object */
  /** @var \Drupal\child_entities\ChildEntityInterface $lecture */
  $form_object = $form_state->getFormObject();
  $lecture = $form_object->getEntity();
  $form_state->setRedirect('entity.paragraph.collection', [
    'course' => $lecture->getParentEntity()->id(),
    'lecture' => $lecture->id(),
  ]);
}

/**
 * Adds abort button to form array.
 */
function lectures_add_abort_button(&$form, $url) {
  $form['actions']['abort'] = [
    '#type' => 'link',
    '#title' => t('Abort'),
    '#url' => $url,
    '#attributes' => [
      'class' => ['button'],
    ],
    '#weight' => 5,
  ];
}
