id: project_invite
langcode: 'de'
text: 'Die Organisation %Organization mit dem Projekt %Project wurde von der %AuthorWithRole eingeladen!'
public_text: 'Die Organisation %Organization mit dem Projekt %Project wurde von %Author eingeladen!'
