<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
//use Drupal\Core\Url;
use Drupal\user\UserInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
//use Drupal\Component\Utility\UrlHelper;
//use Drupal\Core\Entity\Entity\EntityViewDisplay;

/**
 * Implements hook_theme().
 *
 * @inheritdoc
 */
function youvo_theme($existing, $type, $theme, $path) {

  $items = [];

  return $items;
}

/**
 * Implements hook_form_user_login_alter().
 *
 * @inheritdoc
 */
function youvo_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {

//  unset($form['name']['#description']);
//  unset($form['name']['#attributes']['aria-describedby']);
//  unset($form['pass']['#description']);
//  unset($form['pass']['#attributes']['aria-describedby']);
//  $form['name']['#wrapper_attributes']['class'][] = 'c-input--large';
//  $form['pass']['#wrapper_attributes']['class'][] = 'c-input--large';
//  $form['actions']['submit']['#attributes']['class'][] = 'c-button--block';
}

/**
 * Implements hook_user_login().
 *
 * @inheritdoc
 */
function youvo_user_login(AccountInterface $account) {

//  $roles = $account->getRoles();
//  // user.reset.login == reset
//  // user.login == login
//  $route_name = \Drupal::routeMatch()->getRouteName();
//  if ($route_name != 'user.reset.login' && in_array('authenticated', $roles)) {
//    $destination = Url::fromUserInput('/dashboard')->toString();
//    \Drupal::service('request_stack')
//      ->getCurrentRequest()->query->set('destination', $destination);
//  }
}

/**
 * Implements hook_mail().
 *
 * @inheritdoc
 */
function youvo_mail($key, &$message, $params) {

//  switch ($key) {
//    case 'support_message':
//      $message['from'] = $params['from'];
//      $message['subject'] = $params['subject'];
//      $message['body'][] = $params['message'];
//      break;
//  }
}

/**
 * Implements hook_user_view().
 *
 * @inheritdoc
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 *   Thrown if the entity type doesn't exist.
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 *   Thrown if the storage handler couldn't be loaded.
 */
function youvo_user_view(array &$build, UserInterface $account,
                         EntityViewDisplayInterface $display, $view_mode) {

//  // Attach events relevant to user.
//  if ($view_mode == 'full') {
//    $build['#title'] = $account->get('field_name')->value;
//
//    // Initialize component for render array.
//    $build['projects'] = [];
//
//    $display->setComponent('projects', [
//      'type' => 'entity_reference_entity_view',
//      'region' => 'content',
//    ]);
//
//    // Get relevant projects from database.
//    $nids = \Drupal::entityTypeManager()
//      ->getStorage('node')
//      ->getQuery()
//      ->condition('status', 1)
//      ->condition('lc$brokered', 1)
//      ->condition('field_participants', $account->id())
//      ->sort('created', 'DESC')
//      ->execute();
//
//    // Load projects.
//    $projects = \Drupal::entityTypeManager()->getStorage('node')
//      ->loadMultiple($nids);
//
//    // Iterate events and get view.
//    // We do not use viewMultiple here because we want to iterate over events
//    // in the twig template in order to add correct wrappers.
//    // Unfortunately we have to delete a #weight entry in preprocessing later.
//    // See yv_preprocess_user().
//    foreach ($projects as $project) {
//      $build['projects'][] = \Drupal::entityTypeManager()
//        ->getViewBuilder('node')
//        ->view($project, 'teaser');
//    }
//  }
}

/*
 * Implements hook_form_user_edit_form_alter().
 *
 * @inheritdoc
 */
function youvo_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//  $form['#title'] = t('Einstellungen');
//
//  $form['account']['mail']['#description'] = '';
//  $form['account']['current_pass']['#description'] = '';
//  $form['account']['pass']['#description'] = '';
//
//  // Manipulate field skills form wrapper.
//  $form['field_skills']['widget']['#attributes']['class'][] = 'u-text-center';
//  $form['field_skills']['widget']['#title_display'] = 'invisible';
//
//  // Add submit handler second to last.
//  array_splice($form['actions']['submit']['#submit'], -1, 0, 'youvo_form_user_edit_social_link_submit');
}

/*
 * Function to generalize social links on profile pages.
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 *   In case of failures an exception is thrown.
 */
function youvo_form_user_edit_social_link_submit(array &$form, FormStateInterface $form_state) {

//  /** @var \Drupal\user\ProfileForm $form_object */
//  $form_object = $form_state->getFormObject();
//  /** @var \Drupal\user\Entity\User $account */
//  $account = $form_object->getEntity();
//
//  // Extract profile if link was given in xing field.
//  $link_xing = $form_state->getValue('field_xing');
//  $link_xing = $link_xing[0]['value'];
//  if (UrlHelper::isValid($link_xing) && strpos($link_xing, 'xing.com/people') !== FALSE) {
//    $parsed_url = UrlHelper::parse($link_xing);
//    $parsed_url_path = explode('/', $parsed_url['path']);
//    $account->set('field_xing', $parsed_url_path[2]);
//  }
//
//  // Extract profile if link was given in linkedin field.
//  $link_linkedin = $form_state->getValue('field_linkedin');
//  $link_linkedin = $link_linkedin[0]['value'];
//  if (UrlHelper::isValid($link_linkedin) && strpos($link_linkedin, 'linkedin.com/in') !== FALSE) {
//    $parsed_url = UrlHelper::parse($link_linkedin);
//    $parsed_url_path = explode('/', $parsed_url['path']);
//    $account->set('field_linkedin', $parsed_url_path[2]);
//  }
//
//  try {
//    $account->save();
//  } catch (\Exception $e) {
//    watchdog_exception('youvo', $e);
//  }

}

/**
 * Implements hook_page_top().
 *
 * @inheritdoc
 */
function youvo_page_top(array &$page) {

//  // Hide toolbar in non-administrative theme.
//  $current_theme = \Drupal::theme()->getActiveTheme()->getName();
//  if(!($current_theme == 'seven')) {
//    if (isset($page['toolbar'])) {
//      unset($page['toolbar']);
//    }
//  }
}
