<?php

/**
 * @file
 * Custom module which provides implementation of core youvo functionality.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function youvo_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'youvo_user_login_form_submit';
}

/**
 * Custom submit handler for the login form.
 */
function youvo_user_login_form_submit($form, FormStateInterface $form_state) {
  $url = Url::fromRoute('youvo.dashboard');
  $form_state->setRedirectUrl($url);
}

/**
 * Implements hook_theme().
 */
function youvo_theme($existing, $type, $theme, $path) {
  return [
    'dashboard' => [
      'template' => 'content--dashboard',
      'variables' => ['page' => NULL],
    ],
  ];
}
