name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: 8.3
      - name: Validate Dependencies
        run: composer validate
      - name: Install Dependencies
        uses: ramsey/composer-install@v3
      - name: Check Coding Standards
        run: vendor/bin/phpcs --report=summary
      - name: Static Code Analysis
        run: vendor/bin/phpstan analyze web/modules/custom

  test:
    name: Testing
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: no
          php-version: 8.3
      - name: Install Dependencies
        uses: ramsey/composer-install@v3
      - name: Setup Environment
        run: |
          sudo systemctl start mysql.service
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS db;'
          sudo systemctl start apache2.service
      - name: Unit & Kernel Tests
        run: vendor/bin/phpunit --testsuite unit,kernel --testdox --stop-on-failure
      - name: Install Drupal
        run: bash scripts/install-ci.sh
      - name: Existing Site Tests
        run: vendor/bin/phpunit --testsuite existing-site --testdox --stop-on-failure
