name: PHP Code Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  phpanalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP_CodeSniffer and PHPStan
        run: |
          composer require --dev dealerdirect/phpcodesniffer-composer-installer
          composer require --dev drupal/coder

      - name: Check coding standards
        run: |
          vendor/bin/phpcs --report=summary

      - name: Static code analysis
        run: |
          vendor/bin/phpstan analyze web/modules
