name: PHP Code Analysis

on: pull_request

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP CodeSniffer
        run: |
          composer require --dev dealerdirect/phpcodesniffer-composer-installer
          composer require --dev drupal/coder

      - name: Check coding standards
        run: |
          vendor/bin/phpcs --report=summary

      - name: Install PHPStan
        run: |
          composer require --dev 'phpstan/phpstan:^1.5'
          composer require --dev 'phpstan/extension-installer:^1.1'
          composer require --dev 'phpstan-deprecation-rules:^1.0'
          composer require --dev 'mglaman/phpstan-drupal:^1.1'

      - name: Static code analysis
        run: |
          vendor/bin/phpstan analyze web/modules
