<?php

/**
 * @file
 * Alterations for paragraph entity.
 *
 * This module does not define a new quiz entity. A quiz is a paragraph entity
 * or more explicitly a type of paragraph entity. We use the following hooks
 * to implement alterations to extend paragraphs for quizzes.
 */

use Drupal\quizzes\Entity\Quiz;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function quizzes_entity_bundle_info_alter(&$bundles) {
  if (isset($bundles['paragraph']['quiz'])) {
    $bundles['paragraph']['quiz']['class'] = Quiz::class;
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function quizzes_entity_type_alter(array &$entity_types) {
  // We alter the default paragraph.{add,edit} form handlers in order
  // to load a different class than the standard add- and  edit form for
  // paragraphs.
  // @todo Check if there is a better way to define handlers by bundle.
  $entity_types['paragraph']->setFormClass('add', 'Drupal\\quizzes\\Form\\ParagraphWithQuizForm');
  $entity_types['paragraph']->setFormClass('edit', 'Drupal\\quizzes\\Form\\ParagraphWithQuizForm');
}
